$(document).ready(function(){
	$(".page_7_button_13").click(function(){
		window.location.assign("export_data.php?by_service_count_asc=f");
	});
	$(".page_7_button_2").click(function(){
		window.location.assign("export_data.php?by_service_count_desc=f");
	});
	$(".page_7_button_11").click(function(){
		window.location.assign("export_data.php?without_any_reports=f");
	});
	$(".page_7_button_12").click(function(){
		window.location.assign("export_data.php?not_without_any_reports=f");
	});
	$(".page_7_button_1").click(function(){
		window.location.assign("export_data.php?by_report_count_desc=f");
	});
	$(".page_7_button_10").click(function(){
		window.location.assign("export_data.php?by_report_count_asc=f");
	});
	$(".search_box").on('input',function(){
		$.ajax({
			url:"../ajax/search.php?search_key_word="+$(".search_box").val(),
			success:function(data){
				$("#export_container").html(data);
			}
		});
		
	});
});